export const sqliteSchema = [
  `CREATE TABLE IF NOT EXISTS items (
    id TEXT PRIMARY KEY NOT NULL,
    type TEXT NOT NULL,
    status TEXT NOT NULL,
    route TEXT,
    source TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    due_at TEXT,
    review_at TEXT,
    strategy_thread_id TEXT,
    parent_item_id TEXT,
    source_item_id TEXT,
    encrypted_payload TEXT NOT NULL,
    payload_nonce TEXT NOT NULL,
    payload_version INTEGER NOT NULL,
    deleted_at TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_items_inbox ON items(status, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_items_today_due ON items(status, due_at)`,
  `CREATE INDEX IF NOT EXISTS idx_items_review ON items(status, review_at)`,
  `CREATE INDEX IF NOT EXISTS idx_items_strategy_thread ON items(strategy_thread_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS strategy_threads (
    id TEXT PRIMARY KEY NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    next_review_at TEXT,
    encrypted_payload TEXT NOT NULL,
    payload_nonce TEXT NOT NULL,
    payload_version INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS calendar_events (
    id TEXT PRIMARY KEY NOT NULL,
    provider TEXT NOT NULL,
    external_calendar_id TEXT,
    external_event_id TEXT,
    status TEXT NOT NULL,
    starts_at TEXT NOT NULL,
    ends_at TEXT,
    is_all_day INTEGER,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    remote_updated_at TEXT,
    last_synced_at TEXT,
    source_item_id TEXT,
    strategy_thread_id TEXT,
    can_edit INTEGER,
    can_delete INTEGER,
    encrypted_payload TEXT NOT NULL,
    payload_nonce TEXT NOT NULL,
    payload_version INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_calendar_events_starts_at ON calendar_events(starts_at)`,
  `CREATE INDEX IF NOT EXISTS idx_calendar_events_external ON calendar_events(provider, external_calendar_id, external_event_id)`,
  `CREATE TABLE IF NOT EXISTS sync_states (
    provider TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    last_full_sync_at TEXT,
    last_incremental_sync_at TEXT,
    encrypted_sync_token TEXT,
    sync_token_nonce TEXT,
    status TEXT NOT NULL,
    last_error TEXT,
    updated_at TEXT NOT NULL
  )`
] as const;
